export { default as Navbar } from './Navbar'
export { default as About } from './About'
export { default as Publications } from './Publications'
export { default as Services } from './Services'
export { default as Footer } from './Footer'